





# 配置端口
server:
  port: 8083
spring:
  #环境配置
  profiles:
    active: dev
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.112:3306/workuser?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&&allowMultiQueries=true
    username: root
    password: rootroot
    type: com.alibaba.druid.pool.DruidDataSource
  spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 1024MB #最大请求文件的大小
      max-file-size: 2048MB #设置单个文件最大长度
      file-size-threshold: 3000MB #当文件达到多少时进行磁盘写入





    # mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:**/mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


swagger:
  enable: true


#logging:
  #pattern:
    #格式化，只能输出日期和内容
    #console: "%d - %msg%n"

#日志输出磁盘中
#logging:
  #pattern:
   # console: "%d - %msg%n"
  #path: e:/
 # 配置日志输出文件 ，指定文件名
  #file: e:/sell.log

  #uploadFolder: c盘


